# Copyright (c) 2017 ~ 2025, the original author James Gsoing individual Inc,
# All rights reserved. Contact us <springcloudgateway@163.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# #### SpringCloud Gateway Example Service configuration. ####
#
spring:
  redis:
    cluster:
      nodes: ${REDIS_NODES:redis.com:6379,redis.com:6380,redis.com:6381,redis.com:7379,redis.com:7380,redis.com:7381}
    timeout: 10000ms
    password: ${REDIS_PASSWD:123456}
    lettuce:
      pool:
        max-active: 10
        max-wait: -1ms
  cloud:
    discovery:
      client:
        simple:
          instances:
            default-fallback-service:
              - instanceId: default-fallback-service
                uri: http://localhost:${server.port}/_fallback
                metadata: {}

            productpage-service:
              - instanceId: n1.v1-productpage-service:8001
                #uri: http://localhost:8001
                uri: http://httpbin.org/post
                metadata:
                  Iscg-Canary-Label-Header: v1-canary-header
                  Iscg-Canary-Label-Query: v1-canary-query

              - instanceId: n2.v1-productpage-service:8001
                #uri: http://localhost:8001
                uri: http://httpbin.org/post
                metadata:
                  Iscg-Canary-Label-Header: v1-canary-header
                  Iscg-Canary-Label-Query: v1-canary-query

            details-service:
              - instanceId: n1.v1-details-service:8002
                #uri: http://localhost:8002
                uri: https://httpbin.org/post
                metadata:
                  Iscg-Canary-Label-Header: v1-canary-header
                  Iscg-Canary-Label-Query: v1-canary-query

              - instanceId: n2.v1-details-service:8002
                #uri: http://localhost:8002
                uri: https://httpbin.org/post
                metadata:
                  Iscg-Canary-Label-Header: v1-canary-header
                  Iscg-Canary-Label-Query: v1-canary-query

            ratings-service:
              - instanceId: n1.v1-ratings-service:8003
                #uri: https://localhost:8003
                uri: https://httpbin.org/post
                metadata:
                  Iscg-Canary-Label-Header: v1-canary-header
                  Iscg-Canary-Label-Query: v1-canary-query

              - instanceId: n2.v1-ratings-service:8003
                #uri: https://localhost:8003
                uri: https://httpbin.org/post
                metadata:
                  Iscg-Canary-Label-Header: v1-canary-header
                  Iscg-Canary-Label-Query: v1-canary-query

              - instanceId: n3.v2-ratings-service:8003
                #uri: https://localhost:8003
                uri: https://httpbin.org/post
                metadata:
                  Iscg-Canary-Label-Header: v2-canary-header
                  Iscg-Canary-Label-Query: v2-canary-query
